name: RuneCraft
main: com.Greenlock28.RuneCraft.RuneCraft
version: 1.0
load: startup
commands:
   giverune:
      description: Gives the user a rune as specified.
      usage: /giverune [runetype]
      permission: runecraft.giverune
      permission-message: You don't have <permission>